### ISSUE TITLE
Patch from First Turn Media

### ISSUE THREAD

**Issue by jeremylichtman** [cm-advanced/reservations_project_suggestor#2]
The patch attached below fixes a number of issues (pull request is the same code diff, but was created before the workflow was agreed to):

a) Projects do not have a field field_reason_not_active - it looks like the field "reason not active" exists on some sites but not others, or alternatively is left over from the D6 version. When the code checks it, it produces a non-existent property error, which breaks the AJAX call. If the field is actually required, the patch could be re-worked to test for it's presence, and set the resulting variable to true in it's absence.

b) The "has results" variable is being set in the wrong place - the variable $has_results was being set prior to the "if" statement that actually determines whether or not to include a project into the list of picks. This means that the call could return nonsensical results if there are projects for the user, but none that are active.

c) "html" variable isn't being initialized properly - the $html variable was not set at the beginning of the function to an empty string; this was resulting in a php notice, which broke the AJAX response.

d) The js for setting the pick never gets called (looks like it is looking for the wrong field id) - this is either something specific to particular projects, or just a holdover from the D6 version, but the field id for the projects textfield is now called "edit-field-og-node1-und-0-admin-0-target-id", not "edit-og-node1-und-0-admin-0-target-id" (at least on SPNN). As a result, pressing on one of the pick buttons did not set the project in the field. Ideally, we should either have a config setting for the field id, or some way of globally identifying the correct field that doesn't rely on the specific naming schema - i.e. we could possibly check for the wrapper's OG classes, and then sub-select the autocomplete field, or we could use the form alter to push some specific classes in.

e) While I was implementing the items above, I cleaned up indentations and added some missing docblocks.

f) I also added standard classes to buttons, so that they take on the same styling as other buttons within the given theme.

The patch was successfully applied to SPNN.

[fix-ajax-errors.txt](https://github.com/cm-advanced/reservations_project_suggestor/files/1263931/fix-ajax-errors.txt)

**Comment by emilyf** [comment]
This patch has also now successfully been applied to RETN.

**Comment by libkuman** [comment]
Hi Jeremy,

   Thanks for posting the patch and the pull request. This is still all a work in progress but we are really glad to see your code.

   There are somethings that would make things a lot easier on our side to integrate patches.

1. When submitting functionality changes it would be best if you avoided also including large amounts of formatting changes. Most of your changed lines are just formatting changes. If the work is part of a large scale upgrade, with multiple changes it makes sense to include formatting changes, but with smaller stuff we rather be able to just look at functional changes on their own. The way it is now its really hard to find the relevant code changes.

2.  As you can probably see, the modules posted to cma differ a lot in their state, especially in regards to code standards and other things.  These modules were developed by different people, at different times, under different deadline. Moving forward we are trying to have all new code added  follow all the drupal standards, things like 80 character limit. Old code will be cleaned up when it can be bundled into a larger upgrade.

3. As far as when patches and/or pull requests get integrated, it will vary a lot from module to module. Some modules are under a lot of development, and changes will be pulled in quicker. Some modules may never need a new feature and patches will just act as documentation if and when develompment may ever get picked up again in the future.

4. For this specific patch, the field_reason_not_active field should be replaced by  checking the actual status of the project. Project's that are marked as inactive should not show. so $node->status != 0

5.  The edit-og-node1-und-0-admin-0-target-id field should indeed be a configurable field. While this module was written for general use, as far as we are aware it hadn't been used on other stations so its not surprising there was an issue or two. This is low on MNN's priority list right now so it probably won't be changed, especially with the big reservation changes coming down the pipeline (might or might not integrate this code)

6. The other fixes from your descriptions sound clean and right, but its hard for me to find them with all the formatting changes. 

  Let me know if all this makes sense. If you ever want to hop on the phone quickly to discuss more let me know.

best,
Mark Libkuman
Openflows

**Comment by jeremylichtman** [comment]
Hi Mark,

I can reformat this as several single-issue patches, each with it's own issue thread, if that helps.

Regards,

Jeremy

**Comment by libkuman** [comment]
That would be awesome. Much appreciated.

**Comment by jeremylichtman** [comment]
I've added three separate issues, with their own patches. Going to mark this one as closed.

**Comment by libkuman** [comment]
Thanks so much! I really appreciate the effort you took.
